version: 1.0

stages:
  - name: deploy
    image: node:20
    jobs:
      - name: deploy-appsail
        steps:
          - cd /catalyst
          - npm install
          - npm install -g zcatalyst-cli
          - catalyst deploy appsail --name incident-api --verbose
