version: 1.0

runners:
  default:
    config-id: 3

pipeline-when:
  equal:
    - << event.ref >>
    - refs/heads/main

images:
  node:
    image: node:20

jobs:
  deploy-appsail:
    steps:
      - cd /catalyst
      - npm ci
      - npm install -g zcatalyst-cli
      - >-
        catalyst deploy appsail
        --name "incident-api"
        --build-path "/catalyst"
        --stack node20
        --platform nodejs
        --command "node index.js"
        --verbose

stages:
  - name: deploy
    image: node
    jobs:
      - deploy-appsail
